services:
  - type: web
    name: fic-mcq-portal
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d8j4nie7r5hc73dgdqi0-a.oregon-postgres.render.com:5432/fic_portal_nr5q?sslmode=require
      - key: DATABASE_USERNAME
        value: fic_portal_nr5q_user
      - key: DATABASE_PASSWORD
        sync: false
