services:
  - type: web
    name: fic-mcq-portal
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DATABASE_HOST
        value: gondola.proxy.rlwy.net
      - key: DATABASE_PORT
        value: "45898"
      - key: DATABASE_NAME
        value: railway
      - key: DATABASE_USERNAME
        value: postgres
      - key: DATABASE_PASSWORD
        sync: false
