services:
  - type: web
    name: fic-mcq-portal
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DATABASE_HOST
        value: dpg-d8j4nie7r5hc73dgdqi0-a.oregon-postgres.render.com
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_NAME
        value: fic_portal_nr5q
      - key: DATABASE_USERNAME
        value: fic_portal_nr5q_user
      - key: DATABASE_PASSWORD
        sync: false
